[build]
  publish = "_site"
  command = "bun --bun astro build"
  functions = "functions/"

[dev]
command = "bun --bun astro dev"
autoLaunch = false

[[plugins]]
package = "netlify-plugin-purgecss"


# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

# The default HTTP status code is 301, but you can define a different one e.g.
# status = 302

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#   for = "/*"

[[headers]]
for = "/_astro/*"
[headers.values]
cache-control = "public, max-age=31536000"

[[headers]]
for = "/*.svg"
[headers.values]
cache-control = "public, max-age=31536000"

[[headers]]
for = "/*.webp"
[headers.values]
cache-control = "public, max-age=31536000"

[[headers]]
for = "/*.png"
[headers.values]
cache-control = "public, max-age=31536000"

[[headers]]
for = "/*.jpg"
[headers.values]
cache-control = "public, max-age=31536000"

[[headers]]
for = "/*.js"
[headers.values]
cache-control = "public, max-age=31536000"

[[headers]]
for = "/*.css"
[headers.values]
cache-control = "public, max-age=31536000"

#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
